### PR TITLE
Create .env

### PR DESCRIPTION
**Pull request by fandirmadhan**

### CODE REVIEW

**Comment by Santosl2** [comment]
Hey men, i can't merge this because it's your Open AI API keys

**Comment by fandirmadhan** [comment]
sorry dude,im a new user on git

**Comment by joaoaugustogrobe** [comment]
@fandirmadhan you've leaked your Open AI API Key, I would recommend you to delete this key on [Open AI API Keys](https://platform.openai.com/account/api-keys) and create a new one.

**Comment by Santosl2** [comment]
> @fandirmadhan you've leaked your Open AI API Key, I would recommend you to delete this key on [Open AI API Keys](https://platform.openai.com/account/api-keys) and create a new one.

Exactly dude ...

**Pull request closed without merging**
